### ISSUE TITLE
Worker crashing on RpcException

### ISSUE THREAD

**Issue by mfontes** [Azure/azure-functions-nodejs-worker#352] opened 2020-11-24 20:28 UTC
#### Investigative information

- Timestamp: 193 failed operations between 11/24/2020, 11:27:20 AM and 11/24/2020, 11:49:47 AM
- Invocation ID: 6e9924ae-d470-4bfc-939a-65e41c3a3030 (first occurrence) and 6ba54e62-c877-4be2-bddb-acaab5577d41 (last occurrence)
- Region: West US 2

#### Repro steps
1. Invoke the function

#### Expected behavior
1. After invoking the function I expect it to run and ideally finish successfully.

#### Actual behavior
1. Function fails with RpcException and the following error:
```
Exception while executing function: Functions.db_writer Result: Failure
Exception: Worker was unable to load function db_writer: 'Error: UNKNOWN: unknown error, lstat 'D:\home''
Stack: Error: UNKNOWN: unknown error, lstat 'D:\home'
    at Object.realpathSync (fs.js:1615:7)
    at toRealPath (internal/modules/cjs/loader.js:363:13)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:24)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at FunctionLoader.load (D:\Program Files (x86)\SiteExtensions\Functions\3.0.14916\workers\node\worker-bundle.js:20979:22)
    at WorkerChannel.functionLoadRequest (D:\Program Files (x86)\SiteExtensions\Functions\3.0.14916\workers\node\worker-bundle.js:18439:38)
    at ClientDuplexStream.<anonymous> (D:\Program Files (x86)\SiteExtensions\Functions\3.0.14916\workers\node\worker-bundle.js:18343:30) 
```

#### Known workarounds

After waiting 22 minutes, the issue appeared to resolve on its own.

#### Related information 

The function normally runs successfully, but we want to investigate the root cause of this downtime today. We upgraded this function from v2 to v3 3-4 weeks ago, and this is the first time we have seen this issue since then.

* Programming language used - LTS Node v12
* Bindings used - EventHub Trigger
* Function version - v3

**Comment by mfontes** [comment] 2021-10-05 23:08
Any triage update on this issue? We are still seeing this with some regularity. It occurred again today on one of our functions for about 20 minutes.

**Comment by anthonychu** [comment] 2021-12-13 21:48
@mfontes Can you please provide the following information from a more recent invocation, as well as a time range of when the issue last occurred?

> Investigative information
> Timestamp: 193 failed operations between 11/24/2020, 11:27:20 AM and 11/24/2020, 11:49:47 AM
> Invocation ID: 6e9924ae-d470-4bfc-939a-65e41c3a3030 (first occurrence) and 6ba54e62-c877-4be2-bddb-acaab5577d41 (last occurrence)
> Region: West US 2

**Comment by mfontes** [comment] 2021-12-20 17:08
@anthonychu We were seeing this consistently from Wednesday until about 7AM PST this morning (When we manually restarted the functionapp -- did not resolve on its own this time!)

Timestamp: About ~32,000 failures as early as 12/15/2021, 9:09:55.306 PM PST and as late as 12/20/2021, 6:55:20.638 AM PST
InvocationID: 5a4af4a4-58ab-4359-a959-363839b36aa7  (for 12/15 failure) and 149f0a41-bbc2-4fce-a5cc-5986753fb04b (for most recent failure)
Region: West US 2

**Comment by ejizba** [comment] 2023-10-10 22:32
Dupe of https://github.com/Azure/azure-functions-nodejs-worker/issues/693

**Closed as not planned by ejizba** 2023-10-10 22:32 UTC
Labels: Needs: Attention :wave:, investigate
