### ISSUE TITLE
Errors don't show in log stream

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-nodejs-worker#356] opened 2020-12-09 06:45 UTC
Internal issue: https://dev.azure.com/azuretracking/Azure%20tracking/_queries/edit/1703/?triage=true
Also: https://dev.azure.com/azuretracking/Azure%20tracking/_queries/edit/1723/?triage=true
https://dev.azure.com/azuretracking/Azure%20tracking/_queries/edit/1713/?triage=true

If you create a JS function that throws (adding "throw 'error';" in the code for example) and try to stream logs with the command "func azure functionapp logstream <app>" no logs at all are displayed when executing the function.

/cc @sinedied

**Comment by anthonychu** [comment] 2020-12-09 06:46
@mhoeger please take a look at this. It's being flagged as a P1 in Node end to end review.

**Comment by fabiocav** [comment] 2020-12-10 22:51
Primary goal here is for investigation. We need to identify the issue so we can scope and potentially commit to sprint.

**Comment by mhoeger** [comment] 2021-01-13 20:29
Unable to repro this 
<img width="811" alt="Screen Shot 2021-01-13 at 12 27 44 PM" src="https://user-images.githubusercontent.com/8888531/104506892-d9a92e80-559a-11eb-8470-edf5429a700d.png">

Where this is my code:
```
module.exports = async function (context, req) {
    context.log('JavaScript HTTP trigger function processed a request.');
    context.log(process.version);
    if (req.query.error) {
        throw "error";
    }
}
```

**Comment by mhoeger** [comment] 2021-01-14 01:45
@sinedied - sorry for the late response on this by the way! I've tried deploying to a Linux Dedicated app as well as Windows consumption and am unable to repro. Can you give me some more details on when you ran into this behavior? And if you did something like the code above, was it just the failed executions that weren't showing up? Some helpful information would be: core tools version you used and the name of your app and a rough timeframe of when you ran into this issue. You can share your function app name either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly). Thanks!

**Comment by sinedied** [comment] 2021-01-14 13:44
I don't have the Function App deployed anymore, but I'll try to roll up a new one and give you all the details to reproduce. The core tools version I had installed was 3.0.2996, using Node.js v12. The stack trace you show is what I could get using VS Code or the Portal, but using the CLI strangely all I got what nothing.

I'll test again on my current env, then retry with latest core tools/Node.js version and let you know the results.

**Comment by mhoeger** [comment] 2021-01-15 05:13
Thank you @sinedied !

**Comment by sinedied** [comment] 2021-01-18 10:40
@mhoeger I tried publishing the same project I used when I raised this issue, on a new azure function (both windows and linux, Node.js v12 and v14) and could not reproduce the issue I had before, but had some mixed results though.

My process was always the same:
- Use the same functions projects I used for E2E reviews, no code change
- Create a new function app with a new resource group (sometimes on the portal, sometimes on the CLI)
- Deploy through the CLI

One worrying thing is that I experienced some "flakyness" with the platform (out of 5 tries):
- On one instance, when deploying with the func CLI the first time the project on a Linux/Node v12 it succeeded without an error, though no function was actually deployed. It worked then when redeploying with the exact same command the second time
- On one instance, I could never see any logs in the browser portal (--browser option) with a linux instance. Trying again 3 days later, it worked on first try.
- On one instance, deployment got stuck, I killed it and then it kept throwing errors when I tried again for at least an hour (then I went on). And it worked when I tried again the next day.

When I reported the log issue, I tried a few times running the CLI command (at least 3 I as recall) and could never see the logs.
So far it seems I'm unable to find a replication scenario for this particular issue (I promise I won't trash the function app next time I find an issue like this 😉 ), so this could probably be closed.

Though it might be worth opening a lower-priority issue to investigate the "flakyness" (I lack a better word for this), as I suspect the original log stream issue I had was an instance of that. FWIW, when I ran workshops using Functions, every time we had some random issues like this. As I tried to rule out some possible environment issues, I experienced some of the issues on my own machine that went and go over time, while working perfectly fine most of the time, so I'm not sure what's going on here (cc @anthonychu).

Sorry for the long post and not being able to help much here

**Comment by mhoeger** [comment] 2021-01-20 20:32
Thanks for trying and for the extra details @sinedied! I'm going to close this particular issue, but please do file issues and tag folks with more specific details for some of these scenarios. There appear to be a variety of issues that may need investigating individually. 

One thing that I think will help significantly is @Francisco-Gamino and @madelinegordon 's work to have daily automated E2E tests of core scenarios like this (create function app, deploy, test). Adding them here mainly as FYI, but also to alert them that this flakiness is an issue. For example, instead of running E2E tests just once per day with a given build, perhaps few could run multiple of the same e2e scenario of deploy and test in parallel to try to catch flakiness?

**Closed as completed by mhoeger** 2021-01-20 20:32 UTC
Labels: P1, investigate
