### ISSUE TITLE
Error running TypeScript quickstarts (HTTP trigger) 

### ISSUE THREAD

**Issue by ggailey777** [Azure/azure-functions-nodejs-worker#603] opened 2022-06-28 21:09 UTC
I'm getting errors when I try to create a new TypeScript HTTP triggered function from the TypeScript template. When I try to run either from F5 in VS Code or using `npm install/npm start` I get the following error that seems to be coming from our library:

![image](https://user-images.githubusercontent.com/1388263/176285247-2e49ad61-2de6-4789-b673-1b6d1404a50d.png)

#### Investigative information

Please provide the following:

- Timestamp: n/a
- Function App name: localhost
- Function name(s) (as appropriate): n/a
- Invocation ID: n/a
- Region: n/a

#### Repro steps

Provide the steps required to reproduce the problem:
Using the func.exe CLI--these are the steps from the [Functions CLI Quickstart article](https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-cli-typescript):

1. Initialize a TypeScript project: 
    ```console
    func init LocalFunctionProj --typescript
    cd LocalFunctionProj
    ```
2. Create an HTTP triggered function:
    ```console
    func new --name HttpExample --template "HTTP trigger" --authlevel "anonymous"
    ```
3. Start the project locally:
    ```console
    npm install
    npm start
    ```

#### Expected behavior

Function app starts up and waits to accept HTTP requests on localhost:7071

#### Actual behavior

Error occurs during `npm start`:

![image](https://user-images.githubusercontent.com/1388263/176285247-2e49ad61-2de6-4789-b673-1b6d1404a50d.png)

#### Known workarounds

Run the command:

```console
npm i --save-dev @types/node
```

After this command, the `npm start` command succeeds.

#### Related information 

Provide any related information 

* Programming language used: TypeScript template-only
* Links to source: https://github.com/Azure/azure-functions-templates/tree/dev/Functions.Templates/Templates/HttpTrigger-TypeScript
* Bindings used: none

**Comment by ggailey777** [comment] 2022-06-28 22:06
It looks like the workaround added this line to `devDependencies` in the package.json file.
```json
"@types/node": "^18.0.0",
```

**Comment by ejizba** [comment] 2022-06-28 22:11
Hi, this is a duplicate of: https://github.com/Azure/azure-functions-nodejs-worker/issues/587. We changed the default TypeScript templates in both core tools and VS Code to have `"@types/node"` to fix the issue, but I don't think the changes have rolled out yet.

**Closed as not planned by ejizba** 2022-06-28 22:11 UTC
Labels: duplicate
