### ISSUE TITLE
$return a "cookies" object has no effect in V2 - emit warning

### ISSUE THREAD

**Issue by kepikoi** [Azure/azure-functions-nodejs-worker#284] opened 2020-02-20 11:54 UTC
Using `node` runtime it is now possible to send multiple cookies  like documented here https://github.com/Azure/azure-functions-host/issues/2737 

E.g.:

```javascript
module.exports = async function (context, req) {
    context.res = {
        body: "Hello",
        cookies: [{
            name: "kookay",
            value: "2355tgrbf"
        }, {
            name: "kookay2",
            value: "rfdvt54"
        }]
    };
};

/** 
Cookies present in the response:

GET http://localhost:7071/api/hello
200
23ms
Network
Request Headers
Response Headers
Date: Thu, 20 Feb 2020 11:46:25 GMT
Content-Type: text/plain; charset=utf-8
Server: Kestrel
Content-Length: 5
Set-Cookie: kookay=2355tgrbf; path=/
Set-Cookie: kookay2=rfdvt54; path=/
Response Body
**/

```

But it doesn't work using the `$return` binding:

```javascript
module.exports = async function (context, req) {
    return {
        body: "Hello",
        cookies: [{
            name: "kookay",
            value: "2355tgrbf"
        }, {
            name: "kookay2",
            value: "rfdvt54"
        }]
    };
};

/**
No response cookies:
 
GET http://localhost:7071/api/hello
200
15ms
Network
Request Headers
Response Headers
Date: Thu, 20 Feb 2020 11:51:48 GMT
Content-Type: text/plain; charset=utf-8
Server: Kestrel
Content-Length: 5
Response Body
**/
```

**Comment by ahmelsayed** [comment] 2020-02-20 20:34
/cc @mhoeger for FYI

I can repro that using the function from the issue with this function.json

```
{
  "bindings": [
    {
      "authLevel": "function",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "$return"
    }
  ]
}
```

**Comment by ahmelsayed** [comment] 2020-02-20 20:36
Actually I see a [test here](https://github.com/Azure/azure-functions-nodejs-worker/blob/dev/test/end-to-end/testFunctionApp/HttpTriggerSetsCookie/index.js) for that scenario, so I'm not sure if it's a core-tools specific issue?

**Comment by mhoeger** [comment] 2020-02-20 21:51
@kepikoi - what version of functions are you using?

**Comment by kepikoi** [comment] 2020-02-21 08:15
@ahmelsayed I just tested the `$return` case on my azure functions instance and it doesn't seem to work there either. So is it then https://github.com/Azure/azure-functions-host specific?

@mhoeger 
```powershell
PS C:\> func -v
2.7.2184
PS C:\> node -v
v10.19.0
PS C:\> npm -v
6.13.4
PS C:\> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      18362  0
```

**Comment by mhoeger** [comment] 2020-02-21 17:40
@kepikoi - it looks like this is the root cause: https://github.com/Azure/azure-functions-nodejs-worker/issues/228 (sorry took me a bit to remember!)

In V2, we have this issue where HTTP output through $return does not go through the same code path to create an http request. We couldn't change it in V2 because it is a breaking change (there are some weird but nice things you can do in V2 like returning a string and that will directly end up as the body).

Recommendation is to either not use the $return binding or switch to V3. One thing we could do in V2 is to emit a warning if we see someone using cookies + $return. So I'll keep this issue open!

**Comment by ejizba** [comment] 2022-01-28 18:11
Looks like this was already fixed in v3. Only thing left is this:
> One thing we could do in V2 is to emit a warning if we see someone using cookies + $return. So I'll keep this issue open!

But since v2 is pretty old at this point, I will go ahead and close.

**Closed by ejizba** 2022-01-28 18:11 UTC
Labels: enhancement
