### ISSUE TITLE
The charset of content-type request header is ignored

### ISSUE THREAD

**Issue by yoichiro** [Azure/azure-functions-nodejs-worker#168] opened 2019-01-04 08:35 UTC
#### Abstract

It seems that a charset of the content-type response header is ignored in specific case. If a request has an Accept-Charset request header including "utf-16, utf-8" value, the Azure Functions returns a response that has a response body encoded by UTF-16LE ignoring a charset in the "content-type" response header and has a "charset=utf-16" (this means "UTF-16BE") in the "Content-Type" response header, therefore the client cannot handle the response.

#### Expected Behavior

* The Azure Functions should determines the charset of the response body according to the charset that is set as the "content-type" response header by a code without using the "Accept-Charset" request header value. That is, if the "charset=utf-8" specified, the response body charset should become UTF-8. If the "charset=utf-16" or "charset=utf-16be specified, the response body charset should become UTF-16BE. And, if the "charset=utf-16le" specified, the response body charset should become UTF-16LE.
* Otherwise, the charset of the content-type response header should become "charset=utf-16le" to fit the response body UTF-16LE charset. Or, the charset of the response body is changed to "UTF-16BE".

#### Detail of Current Behavior

For example, it assumes that I write the following code to return the UTF-8 content:

```js
module.exports = (context, req) => {
    context.res = {
        status: 200,
        headers: {
            'content-type': 'application/json; charset=utf-8'
        },
        body: {
            'fulfillmentText': 'Hi, Yoichiro!'
        }
    };
    context.done();
};
```

If a request has an Accept-Charset request header with "utf-8" value only, the response is the following:

* Content-Type: application/json; charset=utf-8
* Response Body Charset: UTF-8

This above is a correct behavior.

Next, if a request has an Accept-Charset request header including "utf-16,utf-8", the response is the following:

* Content-Type: application/json; charset=utf-16
* Response Body Charset: UTF-16LE

This is a bad behavior. The reason is follows:

If the response body charset (UTF-16LE) is correct (that is, the content-type response header set by the code should be ignored) as the specification, the "charset=utf-16" of the content type is wrong. Because, the "utf-16" means "UTF-16BE (Big Endian)", not "UTF-16LE (Little Endian)". This specification is described by the [RFC 2781](https://tools.ietf.org/html/rfc2781#section-4.3):

> Text labelled with the "UTF-16" charset might be serialized in either big-endian or little-endian order. If the first two octets of the text is 0xFE followed by 0xFF, then the text can be interpreted as being big-endian. If the first two octets of the text is 0xFF followed by 0xFE, then the text can be interpreted as being little-endian. If the first two octets of the text is not 0xFE followed by 0xFF, and is not 0xFF followed by 0xFE, then the text SHOULD be interpreted as being big-endian.

The response body string returned by the Azure Functions doesn't have any BOM (Byte Order Mark), and the string is labeled as "utf-16" by the content-type. As the result, the response body string must be handled as "UTF-16BE" charset. However, the response body string charset is actually UTF-16LE.

On the other hand, the code above is setting the "charset=utf-8" in the content-type. That is, this means that I want to return the response as UTF-8 string. However, the actual sent response charset is UTF-16(LE), and the actual content-type is replaced with the "charset=utf-16". If the Accept-Charset request header value doesn't have "utf-8", this might be a useful behavior (but, I'm not sure this is correct). But, at least, I expect that the response body charset should become UTF-8 without ignoring the specified charset.

In addition, for example, it assumes that I write the following code:

```js
module.exports = (context, req) => {
    context.res = {
        status: 200,
        headers: {
            'content-type': 'application/json; charset=utf-16le'
        },
        body: {
            'fulfillmentText': 'Hi, Yoichiro!'
        }
    };
    context.done();
};
```

And, If a request has an Accept-Charset request header with "utf-16le,utf-16,utf-8" value, the response is the following:

* Content-Type: application/json; charset=utf-16
* Response Body Charset: UTF-16LE

The content-type value I set is forcibly replaced from "utf-16le" with "utf-16". This is also a bad behavior, I think.

#### Step to Reproduce

Write the following code and deploy it:

```js
module.exports = (context, req) => {
    context.res = {
        status: 200,
        headers: {
            'content-type': 'application/json; charset=utf-8'
        },
        body: {
            'fulfillmentText': 'Hi, Yoichiro!'
        }
    };
    context.done();
};
```

Next, call the function with `curl` command as like the following:

```bash
$ curl -v -X POST -d "{}" -H "Accept-Charset: utf-16,utf-8" <Function URL>
```

You should get the response with "Content-Type: application/json; charset=utf-16" and UTF-16LE response body string.

**Comment by mhoeger** [comment] 2019-01-16 00:30
@yoichiro - Is something like this what you're looking to do?

```
module.exports = (context, req) => {
    const textBuffer = Buffer("Hi, Yoichiro!");
    const text = textBuffer.toString("ucs2");
    context.res = {
        status: 200,
        headers: {
            'content-type': 'application/json; charset=utf-16'
        },
        body: {
            'fulfillmentText': text
        }
    };
    context.done();
};
```
Note the response here is: 
```
HTTP/1.1 200 OK
Date: Wed, 16 Jan 2019 00:27:39 GMT
Content-Type: application/json; charset=utf-16
Server: Kestrel
Content-Length: 70

{
  "fulfillmentText": "楈‬潙捩楨潲"
}
```

**Comment by mhoeger** [comment] 2019-01-16 00:54
@yoichiro - I hope I'm understanding your request correctly... I think you're wondering why the `Accept-Charset` isn't appearing to work for you. [`Accept-Charset`](https://developer.mozilla.org/docs/Web/HTTP/Headers/Accept-Charset) only advertises which character set the client is able to understand. Then, using content negotiation, the server (i.e., your function) selects one of the proposals, uses it and informs the client of its choice within the content-type response header.

Content negotiation is not enabled by default, but does this give you the response you expect?
```javascript
module.exports = (context, req) => {
    context.res = {
        status: 200,
        body: {
            'fulfillmentText': "Hi, Marie!"
        },
        enableContentNegotiation: true
    };
    context.done();
};
```

**Comment by yoichiro** [comment] 2019-01-16 05:34
@mhoeger Unfortunately, this issue was reproduced even if using the `enableContentNegotiation: true`. The behavior of Azure Functions was not changed by using the flag.

I tested the code above with the `enableContentNegotiation: true`, and sent the following request with `curl` command:

```
curl -v -X POST -H "Accept-Charset: utf-16, utf-8" -d "{}" [FUNCTION_ENDPOINT_URL] > res.dump
```
then I received the following response:

```
< HTTP/2 200 
< content-type: application/json; charset=utf-16
< server: Microsoft-IIS/10.0
< set-cookie: ARRAffinity=a2ab54ae3fec303c0fc0bbc1b9407179816a7ef2025ed3cfbeca59dbb92cd4e3;Path=/;HttpOnly;Domain=yoichirofa1.azurewebsites.net
< x-powered-by: ASP.NET
< set-cookie: ARRAffinity=f50f1ab36aa891469611200488fc7647846e920ef70f8c603af08483120af1bf;Path=/;HttpOnly;Domain=yoichirofa1.azurewebsites.net
< date: Wed, 16 Jan 2019 05:18:59 GMT
< 
{ [64 bytes data]
100    66    0    64  100     2     90      2  0:00:01 --:--:--  0:00:01    90
* Connection #0 to host yoichirofa1.azurewebsites.net left intact
```

* content-type: `application/json; charset=utf-16` (the `utf-16` actually means `UTF-16BE`).
* Response body: The following byes encoded with `UTF-16LE`:

```
$ xxd res.dump
00000000: 7b00 2200 6600 7500 6c00 6600 6900 6c00  {.".f.u.l.f.i.l.
00000010: 6c00 6d00 6500 6e00 7400 5400 6500 7800  l.m.e.n.t.T.e.x.
00000020: 7400 2200 3a00 2200 4800 6900 2c00 2000  t.".:.".H.i.,. .
00000030: 4d00 6100 7200 6900 6500 2100 2200 7d00  M.a.r.i.e.!.".}.
```

The response is wrong, because **charsets of the response header (UTF-16BE) and response body (UTF-16LE) are different**. Both charsets must be same and both must become either UTF-16BE or UTF-16LE. That is, I think that Azure Functions must be fixed so that a same charset is applied for both response header and response body.

**Comment by yoichiro** [comment] 2019-01-21 21:55
@mhoeger Is [the information above](https://github.com/Azure/azure-functions-nodejs-worker/issues/168#issuecomment-454657844) enough for you?

**Comment by mrgrain** [comment] 2019-01-22 16:03
I can reproduce this issue here and suffering from the same defect. Azure functions seems to ignore my carefully crafted content-type response header and does it's own content negotiation anyway.

One could re-phrase the bug as "Content negotiation is on by default and cannot be turned off" (though @yoichiro's report is far more comprehensive)

**Comment by IGx89** [comment] 2019-01-22 17:49
Nice job investigating this, @yoichiro! I reported something similar to this a couple months ago and they said they were going to investigate content-type being ignored as well: https://github.com/Azure/azure-functions-host/issues/3435. However the utf-16be/le issue you identified is probably the bigger issue, since we wouldn't have any need to set content-type if Azure Functions was doing it correctly itself.

**Comment by yoichiro** [comment] 2019-01-22 22:30
> However the utf-16be/le issue you identified is probably the bigger issue, since we wouldn't have any need to set content-type if Azure Functions was doing it correctly itself.

Yes, at least, I believe that the UTF-16LE/BE issue is a bug which must be fixed.

**Comment by yoichiro** [comment] 2019-01-24 20:23
@mhoeger Thank you for handling this issue! Feel free to hear me if you have some question about the behavior of this issue.

**Comment by mhoeger** [comment] 2019-03-13 01:29
@yoichiro - I'm so sorry about the delay on this! I've finally gotten the chance to look into this, and I think that (as @mrgrain) suggested, there is some automatic content negotiation going on when there should not be that's producing the undesirable behavior (of making the body UTF-16LE).

The way I'm going to suggest going around it is to make sure that the content body returned is actually encoded the way you want it to be returned. 

To return UTF-16LE:
```javascript
module.exports = (context, req) => {
    const responseBody = {
        'fulfillmentText': 'Hi, Yoichiro!'
    };
    context.res = {
        status: 200,
        headers: {
            'content-type': 'application/json; charset=utf-16le'
        },
        body: Buffer.from(JSON.stringify(responseBody), "utf-16le")
    };
    context.done();
};
```

To return UTF-16BE:
```javascript
module.exports = (context, req) => {
    const responseBody = {
        'fulfillmentText': 'Hi, Yoichiro!'
    };
    context.res = {
        status: 200,
        headers: {
            'content-type': 'application/json; charset=utf-16'
        },
        body: Buffer.from(JSON.stringify(responseBody), "utf-16le").swap16() // currently no "utf16be" encoding in node
    };
    context.done();
};
```

We're still looking into this issue because we should either be doing no content negotiation (not caring about what the request's accept header is) or doing it properly.

**Comment by mhoeger** [comment] 2019-03-13 02:25
@yoichiro - could you please outline your situation a little better for us too?

We're looking into the issue a little deeper, and it looks like we are following the default behavior of ASP.NET Core. We could add code to allow you and others to override the request's accept-charset, but we'd like to understand your scenario a little better.

In the RFC, it also says the following:

> All applications that process text with the "UTF-16" charset label **MUST** be able to interpret both big endian and little-endian text.

I think this would suggest that the client should be able to handle either by the specifications?

**Comment by yoichiro** [comment] 2019-03-13 13:45
@mhoeger Thank you for the confirmation. I try to describe my situation again.

> > All applications that process text with the "UTF-16" charset label MUST be able to interpret both big endian and little-endian text.

> I think this would suggest that the client should be able to handle either by the specifications?

I have already described about how to understand this specification (how to decide whether a string is encoded by UTF-16LE or UTF-16BE) in the description of this issue. I quote that below.

> > Text labelled with the "UTF-16" charset might be serialized in either big-endian or little-endian order. If the first two octets of the text is 0xFE followed by 0xFF, then the text can be interpreted as being big-endian. If the first two octets of the text is 0xFF followed by 0xFE, then the text can be interpreted as being little-endian. If the first two octets of the text is not 0xFE followed by 0xFF, and is not 0xFF followed by 0xFE, then the text SHOULD be interpreted as being big-endian.

> The response body string returned by the Azure Functions doesn't have any BOM (Byte Order Mark), and the string is labeled as "utf-16" by the content-type. As the result, the response body string must be handled as "UTF-16BE" charset. However, the response body string charset is actually UTF-16LE.

Here is the thing. In RFC2781, we must decide the encoding of **the string labelled with the "UTF-16"** by the following rule:

* If the string starts with `0xFE 0xFF` -> the encoding is UTF-16BE.
* If the string starts with `0xFF 0xFE` -> the encoding is UTF-16LE.
* **Otherwise** -> the encoding is **UTF-16BE**.

The bytes `0xFE 0xFF` is called as "a big-endian BOM". The bytes `0xFF 0xFE` is called as "a little-endian BOM". That is, **if a string labelled with the UTF-16 and it doesn't have any BOM, the encoding of the string is UTF-16BE**.

> > All applications that process text with the "UTF-16" charset label MUST be able to interpret both big endian and little-endian text.

This means that "All applications that process text with the "UTF-16" charset label MUST be able to interpret both big endian and little-endian text (**according to the rule above**)".

And, the target case is like the following situation:

* The client sends a request, which the Accept-Charset has "..., **utf-16**, utf8, ...".
* My function code responds with the code below:

```js
module.exports = (context, req) => {
    context.res = {
        status: 200,
        headers: {
            'content-type': 'application/json; charset=utf-8'
        },
        body: {
            'fulfillmentText': 'Hi, Yoichiro!'
        }
    };
    context.done();
};
```

My expected behavior is:

* The response header contains "Content-Type" application/json; charset=utf-8".
* The response body is a byte array which was encoded by "UTF-8".

However, the actual behavior was:

* The response header contained "Content-Type" application/json; charset=**utf-16**".
* The response body was a byte array which was encoded by "**UTF-16LE (no BOM)**".

There were the following wrong points:

* I specified the "utf-8" charset. But, the "utf-16" was used automatically.
* The "charset=utf-16" means **the string labelled with the "UTF-16"**. That is, if the string doesn't have any BOM, the encoding of the string must be "UTF-16BE" according to the specification described above. However, the actual response body was encoded by "UTF-16LE (no BOM)".

As the result, the client reports an error or shows the garbage characters.

So, in the cases you mentioned at the previous comment,

```js
module.exports = (context, req) => {
    const responseBody = {
        'fulfillmentText': 'Hi, Yoichiro!'
    };
    context.res = {
        status: 200,
        headers: {
            'content-type': 'application/json; charset=utf-16le'
        },
        body: Buffer.from(JSON.stringify(responseBody), "utf-16le")
    };
    context.done();
};
```

The code above doesn't work. Actually, the actual "Content-Type" response header is "Content-Type: application/json; charset=utf-16". I don't know the reason, but, if I specify the "charset=utf-16**le**", the actual value is "charset-utf-16". On the other hand, the response body encoding is UTF-16LE (no BOM). That is, this is the same as the code above. The client will report an error or will show the garbage characters.

```js
module.exports = (context, req) => {
    const responseBody = {
        'fulfillmentText': 'Hi, Yoichiro!'
    };
    context.res = {
        status: 200,
        headers: {
            'content-type': 'application/json; charset=utf-16'
        },
        body: Buffer.from(JSON.stringify(responseBody), "utf-16le").swap16() // currently no "utf16be" encoding in node
    };
    context.done();
};
```

Actually, this code would work. However, why do I need to create a UTF-16BE bytes by myself? I think that this code is ok as workaround for this issue. Fundamentally, if the "charset=utf-16" is specified and the plain string is specified to the body property, the framework must return the response body encoded by "UTF-16BE" or "UTF-16LE (including little-endian BOM)", I expect.

**Comment by ekurutepe** [comment] 2019-08-06 08:17
@mhoeger is there any update on this issue? I'm running into this while trying to serve an ISO-8859-1 encoded XML file:
```
context.res = {
            body: context.bindings.inputStorage,
            headers: {
                'Content-Type': 'text/xml; charset=ISO-8859-1'
            }
        } 
```

But I always get: 
```
< Content-Length: 776809
< Content-Type: text/xml; charset=utf-8
< Server: Kestrel
< Request-Context: appId=cid-v1:a116489e-b2f9-4dce-aa75-a817c0b9bce9
< Date: Tue, 06 Aug 2019 08:16:51 GMT
```

**Comment by AnthonyPhan** [comment] 2020-02-17 07:48
We are also experiencing this issue here. Is there any update?

**Comment by lilyjma** [comment] 2022-05-29 01:47
@AnthonyPhan / @ekurutepe -- Are you still experiencing the issue?

**Comment by ekurutepe** [comment] 2022-05-29 18:43
@lilyjma no idea, it's been 3 years. I don't remember what this was about but I guess I'm not using Azure for it anymore.

**Comment by ejizba** [comment] 2023-09-13 22:20
I spent some time investigating this bug. I was able to repro, but as mentioned above there is a workaround. Fortunately, this bug does _not_ repro for the new model v4, likely because we made several changes to the http types. If you're not familiar with model v4, see the [upgrade guide here](https://learn.microsoft.com/azure/azure-functions/functions-node-upgrade-v4) for more details.

Trying to fix this for the v3 model would be difficult because people could be relying on the old behavior. Since there is a workaround for v3 and this is already fixed in v4, I'll go ahead and close this issue.

## Repro code for model v3

```javascript
module.exports = async function (context, req) {
    context.res = {
        headers: {
            "content-type": `text/plain; charset=ISO-8859-1`,
        },
        body: "Hello world",
    };
};
```

Expected: The response charset is set to `ISO-8859-1`
Actual: The response charset is set to `charset=utf-8`

## Workaround code for model v3

Encode the body as a buffer using the intended charset before returning the response. I used the popular [iconv-lite](https://www.npmjs.com/package/iconv-lite) npm package to help since many encodings are not supported natively by Node.js.

```javascript
const iconvLite = require('iconv-lite');

module.exports = async function (context, req) {
    const charset = 'ISO-8859-1';
    context.res = {
        status: 200,
        headers: {
            "content-type": `text/plain; charset=${charset}`,
        },
        body: iconvLite.encode("Hello world", charset),
    };
};
```

## Example code for model v4 that works as-is

```javascript
const { app } = require("@azure/functions");

app.http("httpTrigger1", {
    methods: ["GET", "POST"],
    authLevel: "anonymous",
    handler: async (request, context) => {
        return {
            body: "Hello world",
            headers: {
                "content-type": "text/plain; charset=ISO-8859-1",
            },
        };
    },
});
```

**Closed by ejizba** 2023-09-13 22:20 UTC
Labels: bug, breaking, P2, investigate
