### ISSUE TITLE
Support running on M1 Macs [Node.js]

### ISSUE THREAD

**Issue by joelvarty** [Azure/azure-functions-nodejs-worker#386] opened 2021-02-07 18:14 UTC
Trying to get an azure function project running on an M1 Macbook Pro.

I think the main issue is this - any ideas for a workaround?

```
Expected directory: node-v72-darwin-arm64-unknown
[2021-02-07T18:11:29.923Z] Found: [node-v57-darwin-ia32-unknown, node-v57-darwin-x64-unknown, node-v57-linux-ia32-glibc, node-v57-linux-x64-glibc, node-v57-win32-ia32-unknown, node-v57-win32-x64-unknown, node-v64-darwin-ia32-unknown, node-v64-darwin-x64-unknown, node-v64-linux-ia32-glibc, node-v64-linux-x64-glibc, node-v64-win32-ia32-unknown, node-v64-win32-x64-unknown, node-v72-darwin-ia32-unknown, node-v72-darwin-x64-unknown, node-v72-linux-ia32-glibc, node-v72-linux-x64-glibc, node-v72-win32-ia32-unknown, node-v72-win32-x64-unknown, node-v83-darwin-ia32-unknown, node-v83-darwin-x64-unknown, node-v83-linux-ia32-glibc, node-v83-linux-x64-glibc, node-v83-win32-ia32-unknown, node-v83-win32-x64-unknown]
[2021-02-07T18:11:29.923Z] This problem can often be fixed by running "npm rebuild" on the current system
[2021-02-07T18:11:29.923Z] Original error: Cannot find module '/opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/grpc/src/node/extension_binary/node-v72-darwin-arm64-unknown/grpc_node.node'
```

Full command output below:

```
func start --verbose

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %


Azure Functions Core Tools
Core Tools Version:       3.0.3233 Commit hash: d1772f733802122a326fa696dd4c086292ec0171 
Function Runtime Version: 3.0.15193.0

[2021-02-07T18:11:27.961Z] Building host: startup suppressed: 'False', configuration suppressed: 'False', startup operation id: '8dd16de4-64f9-408e-9363-ff1fda06bb23'
[2021-02-07T18:11:28.010Z] Reading host configuration file '/Users/joelvarty/Documents/Dev/microsoft/azurefunctiontests/host.json'
[2021-02-07T18:11:28.013Z] Host configuration file read:
[2021-02-07T18:11:28.013Z] {
[2021-02-07T18:11:28.013Z]   "version": "2.0",
[2021-02-07T18:11:28.013Z]   "logging": {
[2021-02-07T18:11:28.013Z]     "applicationInsights": {
[2021-02-07T18:11:28.013Z]       "samplingSettings": {
[2021-02-07T18:11:28.013Z]         "isEnabled": true,
[2021-02-07T18:11:28.013Z]         "excludedTypes": "Request"
[2021-02-07T18:11:28.013Z]       }
[2021-02-07T18:11:28.013Z]     }
[2021-02-07T18:11:28.013Z]   },
[2021-02-07T18:11:28.013Z]   "extensionBundle": {
[2021-02-07T18:11:28.013Z]     "id": "Microsoft.Azure.Functions.ExtensionBundle",
[2021-02-07T18:11:28.013Z]     "version": "[1.*, 2.0.0)"
[2021-02-07T18:11:28.013Z]   }
[2021-02-07T18:11:28.013Z] }
[2021-02-07T18:11:28.049Z] Loading functions metadata
[2021-02-07T18:11:28.085Z] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language:python
[2021-02-07T18:11:28.092Z] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language:java
[2021-02-07T18:11:28.094Z] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language:powershell
[2021-02-07T18:11:28.113Z] Reading functions metadata
[2021-02-07T18:11:28.135Z] 1 functions found
[2021-02-07T18:11:28.149Z] 1 functions loaded
[2021-02-07T18:11:28.158Z] Looking for extension bundle Microsoft.Azure.Functions.ExtensionBundle at /Users/joelvarty/.azure-functions-core-tools/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle
[2021-02-07T18:11:28.163Z] Found a matching extension bundle at /Users/joelvarty/.azure-functions-core-tools/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/1.5.1
[2021-02-07T18:11:28.165Z] Fetching information on versions of extension bundle Microsoft.Azure.Functions.ExtensionBundle available on https://functionscdn.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/index.json
[2021-02-07T18:11:28.368Z] Skipping bundle download since it already exists at path /Users/joelvarty/.azure-functions-core-tools/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/1.5.1
[2021-02-07T18:11:28.382Z] Loading extension bundle from /Users/joelvarty/.azure-functions-core-tools/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/1.5.1/bin
[2021-02-07T18:11:28.397Z] Reading host configuration file '/Users/joelvarty/Documents/Dev/microsoft/azurefunctiontests/host.json'
[2021-02-07T18:11:28.397Z] Host configuration file read:
[2021-02-07T18:11:28.397Z] {
[2021-02-07T18:11:28.397Z]   "version": "2.0",
[2021-02-07T18:11:28.397Z]   "logging": {
[2021-02-07T18:11:28.397Z]     "applicationInsights": {
[2021-02-07T18:11:28.397Z]       "samplingSettings": {
[2021-02-07T18:11:28.403Z]         "isEnabled": true,
[2021-02-07T18:11:28.403Z]         "excludedTypes": "Request"
[2021-02-07T18:11:28.403Z]       }
[2021-02-07T18:11:28.403Z]     }
[2021-02-07T18:11:28.403Z]   },
[2021-02-07T18:11:28.403Z]   "extensionBundle": {
[2021-02-07T18:11:28.403Z]     "id": "Microsoft.Azure.Functions.ExtensionBundle",
[2021-02-07T18:11:28.403Z]     "version": "[1.*, 2.0.0)"
[2021-02-07T18:11:28.403Z]   }
[2021-02-07T18:11:28.403Z] }
[2021-02-07T18:11:28.782Z] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language:python
[2021-02-07T18:11:28.784Z] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language:java
[2021-02-07T18:11:28.784Z] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language:powershell
[2021-02-07T18:11:28.909Z] Initializing Warmup Extension.
[2021-02-07T18:11:28.987Z] Initializing Host. OperationId: '8dd16de4-64f9-408e-9363-ff1fda06bb23'.
[2021-02-07T18:11:28.995Z] Host initialization: ConsecutiveErrors=0, StartupCount=1, OperationId=8dd16de4-64f9-408e-9363-ff1fda06bb23
[2021-02-07T18:11:29.020Z] LoggerFilterOptions
[2021-02-07T18:11:29.020Z] {
[2021-02-07T18:11:29.020Z]   "MinLevel": "None",
[2021-02-07T18:11:29.020Z]   "Rules": [
[2021-02-07T18:11:29.020Z]     {
[2021-02-07T18:11:29.020Z]       "ProviderName": null,
[2021-02-07T18:11:29.020Z]       "CategoryName": null,
[2021-02-07T18:11:29.020Z]       "LogLevel": null,
[2021-02-07T18:11:29.020Z]       "Filter": "<AddFilter>b__0"
[2021-02-07T18:11:29.021Z]     },
[2021-02-07T18:11:29.021Z]     {
[2021-02-07T18:11:29.021Z]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[2021-02-07T18:11:29.021Z]       "CategoryName": null,
[2021-02-07T18:11:29.021Z]       "LogLevel": "None",
[2021-02-07T18:11:29.021Z]       "Filter": null
[2021-02-07T18:11:29.021Z]     },
[2021-02-07T18:11:29.021Z]     {
[2021-02-07T18:11:29.021Z]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[2021-02-07T18:11:29.021Z]       "CategoryName": null,
[2021-02-07T18:11:29.021Z]       "LogLevel": null,
[2021-02-07T18:11:29.021Z]       "Filter": "<AddFilter>b__0"
[2021-02-07T18:11:29.021Z]     },
[2021-02-07T18:11:29.021Z]     {
[2021-02-07T18:11:29.021Z]       "ProviderName": "Azure.Functions.Cli.Diagnostics.ColoredConsoleLoggerProvider",
[2021-02-07T18:11:29.021Z]       "CategoryName": null,
[2021-02-07T18:11:29.021Z]       "LogLevel": null,
[2021-02-07T18:11:29.021Z]       "Filter": "<AddFilter>b__0"
[2021-02-07T18:11:29.021Z]     }
[2021-02-07T18:11:29.021Z]   ]
[2021-02-07T18:11:29.021Z] }
[2021-02-07T18:11:29.022Z] LoggerFilterOptions
[2021-02-07T18:11:29.022Z] {
[2021-02-07T18:11:29.022Z]   "MinLevel": "None",
[2021-02-07T18:11:29.022Z]   "Rules": [
[2021-02-07T18:11:29.022Z]     {
[2021-02-07T18:11:29.022Z]       "ProviderName": null,
[2021-02-07T18:11:29.022Z]       "CategoryName": null,
[2021-02-07T18:11:29.022Z]       "LogLevel": null,
[2021-02-07T18:11:29.025Z]       "Filter": "<AddFilter>b__0"
[2021-02-07T18:11:29.025Z]     },
[2021-02-07T18:11:29.025Z]     {
[2021-02-07T18:11:29.025Z]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[2021-02-07T18:11:29.025Z]       "CategoryName": null,
[2021-02-07T18:11:29.025Z]       "LogLevel": "None",
[2021-02-07T18:11:29.025Z]       "Filter": null
[2021-02-07T18:11:29.025Z]     },
[2021-02-07T18:11:29.025Z]     {
[2021-02-07T18:11:29.025Z]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[2021-02-07T18:11:29.025Z]       "CategoryName": null,
[2021-02-07T18:11:29.025Z]       "LogLevel": null,
[2021-02-07T18:11:29.025Z]       "Filter": "<AddFilter>b__0"
[2021-02-07T18:11:29.025Z]     },
[2021-02-07T18:11:29.025Z]     {
[2021-02-07T18:11:29.025Z]       "ProviderName": "Azure.Functions.Cli.Diagnostics.ColoredConsoleLoggerProvider",
[2021-02-07T18:11:29.025Z]       "CategoryName": null,
[2021-02-07T18:11:29.026Z]       "LogLevel": null,
[2021-02-07T18:11:29.026Z]       "Filter": "<AddFilter>b__0"
[2021-02-07T18:11:29.026Z]     }
[2021-02-07T18:11:29.026Z]   ]
[2021-02-07T18:11:29.026Z] }
[2021-02-07T18:11:29.026Z] FunctionResultAggregatorOptions
[2021-02-07T18:11:29.026Z] {
[2021-02-07T18:11:29.026Z]   "BatchSize": 1000,
[2021-02-07T18:11:29.026Z]   "FlushTimeout": "00:00:30",
[2021-02-07T18:11:29.026Z]   "IsEnabled": true
[2021-02-07T18:11:29.026Z] }
[2021-02-07T18:11:29.026Z] SingletonOptions
[2021-02-07T18:11:29.026Z] {
[2021-02-07T18:11:29.026Z]   "LockPeriod": "00:00:15",
[2021-02-07T18:11:29.026Z]   "ListenerLockPeriod": "00:00:15",
[2021-02-07T18:11:29.026Z]   "LockAcquisitionTimeout": "10675199.02:48:05.4775807",
[2021-02-07T18:11:29.026Z]   "LockAcquisitionPollingInterval": "00:00:05",
[2021-02-07T18:11:29.026Z]   "ListenerLockRecoveryPollingInterval": "00:01:00"
[2021-02-07T18:11:29.026Z] }
[2021-02-07T18:11:29.026Z] HttpOptions
[2021-02-07T18:11:29.026Z] {
[2021-02-07T18:11:29.026Z]   "DynamicThrottlesEnabled": false,
[2021-02-07T18:11:29.026Z]   "MaxConcurrentRequests": -1,
[2021-02-07T18:11:29.026Z]   "MaxOutstandingRequests": -1,
[2021-02-07T18:11:29.026Z]   "RoutePrefix": "api"
[2021-02-07T18:11:29.026Z] }
[2021-02-07T18:11:29.028Z] Starting JobHost
[2021-02-07T18:11:29.034Z] Starting Host (HostId=macbookpro-1282054074, InstanceId=e0e35781-d3a1-427c-a726-fc8fa5f37c83, Version=3.0.15193.0, ProcessId=28989, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=(null))
[2021-02-07T18:11:29.054Z] Loading functions metadata
[2021-02-07T18:11:29.060Z] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language:python
[2021-02-07T18:11:29.061Z] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language:java
[2021-02-07T18:11:29.061Z] FUNCTIONS_WORKER_RUNTIME set to node. Skipping WorkerConfig for language:powershell
[2021-02-07T18:11:29.074Z] Loading proxies metadata
[2021-02-07T18:11:29.080Z] Initializing Azure Function proxies
[2021-02-07T18:11:29.485Z] 0 proxies loaded
[2021-02-07T18:11:29.508Z] 1 functions loaded
[2021-02-07T18:11:29.669Z] Generating 1 job function(s)
[2021-02-07T18:11:29.764Z] Found the following functions:
[2021-02-07T18:11:29.764Z] Host.Functions.test
[2021-02-07T18:11:29.764Z] 
[2021-02-07T18:11:29.806Z] Initializing function HTTP routes
[2021-02-07T18:11:29.806Z] Mapped function route 'api/test' [get,post] to 'test'
[2021-02-07T18:11:29.806Z] 
[2021-02-07T18:11:29.819Z] Host initialized (770ms)
[2021-02-07T18:11:29.828Z] Host started (791ms)
[2021-02-07T18:11:29.828Z] Job host started
[2021-02-07T18:11:29.860Z] internal/modules/cjs/loader.js:818
[2021-02-07T18:11:29.860Z]   throw err;
[2021-02-07T18:11:29.860Z]   ^
[2021-02-07T18:11:29.862Z] Error: Cannot find module './Worker.js'
[2021-02-07T18:11:29.864Z] Expected directory: node-v72-darwin-arm64-unknown
[2021-02-07T18:11:29.864Z] Found: [node-v57-darwin-ia32-unknown, node-v57-darwin-x64-unknown, node-v57-linux-ia32-glibc, node-v57-linux-x64-glibc, node-v57-win32-ia32-unknown, node-v57-win32-x64-unknown, node-v64-darwin-ia32-unknown, node-v64-darwin-x64-unknown, node-v64-linux-ia32-glibc, node-v64-linux-x64-glibc, node-v64-win32-ia32-unknown, node-v64-win32-x64-unknown, node-v72-darwin-ia32-unknown, node-v72-darwin-x64-unknown, node-v72-linux-ia32-glibc, node-v72-linux-x64-glibc, node-v72-win32-ia32-unknown, node-v72-win32-x64-unknown, node-v83-darwin-ia32-unknown, node-v83-darwin-x64-unknown, node-v83-linux-ia32-glibc, node-v83-linux-x64-glibc, node-v83-win32-ia32-unknown, node-v83-win32-x64-unknown]
[2021-02-07T18:11:29.865Z] This problem can often be fixed by running "npm rebuild" on the current system
[2021-02-07T18:11:29.866Z] Original error: Cannot find module '/opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/grpc/src/node/extension_binary/node-v72-darwin-arm64-unknown/grpc_node.node'
[2021-02-07T18:11:29.866Z] Require stack:
[2021-02-07T18:11:29.866Z] - /opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/worker-bundle.js
[2021-02-07T18:11:29.866Z] - /opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/dist/src/nodejsWorker.js
[2021-02-07T18:11:29.866Z] Require stack:
[2021-02-07T18:11:29.866Z] - /opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/dist/src/nodejsWorker.js
[2021-02-07T18:11:29.866Z]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
[2021-02-07T18:11:29.866Z]     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
[2021-02-07T18:11:29.866Z]     at Module.require (internal/modules/cjs/loader.js:887:19)
[2021-02-07T18:11:29.866Z]     at require (internal/modules/cjs/helpers.js:74:18)
[2021-02-07T18:11:29.866Z]     at Object.<anonymous> (/opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/dist/src/nodejsWorker.js:45:14)
[2021-02-07T18:11:29.866Z]     at Module._compile (internal/modules/cjs/loader.js:999:30)
[2021-02-07T18:11:29.866Z]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
[2021-02-07T18:11:29.867Z]     at Module.load (internal/modules/cjs/loader.js:863:32)
[2021-02-07T18:11:29.867Z]     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
[2021-02-07T18:11:29.867Z]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
[2021-02-07T18:11:29.867Z]   code: 'MODULE_NOT_FOUND',
[2021-02-07T18:11:29.867Z]   requireStack: [
[2021-02-07T18:11:29.867Z]     '/opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/dist/src/nodejsWorker.js'
[2021-02-07T18:11:29.867Z]   ]
[2021-02-07T18:11:29.867Z] }
[2021-02-07T18:11:29.922Z] Expected directory: node-v72-darwin-arm64-unknown
[2021-02-07T18:11:29.923Z] Found: [node-v57-darwin-ia32-unknown, node-v57-darwin-x64-unknown, node-v57-linux-ia32-glibc, node-v57-linux-x64-glibc, node-v57-win32-ia32-unknown, node-v57-win32-x64-unknown, node-v64-darwin-ia32-unknown, node-v64-darwin-x64-unknown, node-v64-linux-ia32-glibc, node-v64-linux-x64-glibc, node-v64-win32-ia32-unknown, node-v64-win32-x64-unknown, node-v72-darwin-ia32-unknown, node-v72-darwin-x64-unknown, node-v72-linux-ia32-glibc, node-v72-linux-x64-glibc, node-v72-win32-ia32-unknown, node-v72-win32-x64-unknown, node-v83-darwin-ia32-unknown, node-v83-darwin-x64-unknown, node-v83-linux-ia32-glibc, node-v83-linux-x64-glibc, node-v83-win32-ia32-unknown, node-v83-win32-x64-unknown]
[2021-02-07T18:11:29.923Z] This problem can often be fixed by running "npm rebuild" on the current system
[2021-02-07T18:11:29.923Z] Original error: Cannot find module '/opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/grpc/src/node/extension_binary/node-v72-darwin-arm64-unknown/grpc_node.node'
[2021-02-07T18:11:29.923Z] Require stack:
[2021-02-07T18:11:29.923Z] - /opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/worker-bundle.js
[2021-02-07T18:11:29.923Z] - /opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/dist/src/nodejsWorker.js
[2021-02-07T18:11:29.923Z] internal/modules/cjs/loader.js:818
[2021-02-07T18:11:29.923Z]   throw err;
[2021-02-07T18:11:29.923Z]   ^
[2021-02-07T18:11:29.923Z] Error: Cannot find module './Worker.js'
[2021-02-07T18:11:29.923Z] Require stack:
[2021-02-07T18:11:29.923Z] - /opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/dist/src/nodejsWorker.js
[2021-02-07T18:11:29.924Z]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
[2021-02-07T18:11:29.924Z]     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
[2021-02-07T18:11:29.925Z]     at Module.require (internal/modules/cjs/loader.js:887:19)
[2021-02-07T18:11:29.925Z]     at require (internal/modules/cjs/helpers.js:74:18)
[2021-02-07T18:11:29.925Z]     at Object.<anonymous> (/opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/dist/src/nodejsWorker.js:45:14)
[2021-02-07T18:11:29.964Z]     at Module._compile (internal/modules/cjs/loader.js:999:30)
[2021-02-07T18:11:29.965Z]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
[2021-02-07T18:11:29.965Z]     at Module.load (internal/modules/cjs/loader.js:863:32)
[2021-02-07T18:11:29.965Z]     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
[2021-02-07T18:11:29.965Z]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
[2021-02-07T18:11:29.965Z]   code: 'MODULE_NOT_FOUND',
[2021-02-07T18:11:29.965Z]   requireStack: [
[2021-02-07T18:11:29.965Z]     '/opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/dist/src/nodejsWorker.js'
[2021-02-07T18:11:29.965Z]   ]
[2021-02-07T18:11:29.965Z] }
[2021-02-07T18:11:30.013Z] Expected directory: node-v72-darwin-arm64-unknown
[2021-02-07T18:11:30.014Z] Found: [node-v57-darwin-ia32-unknown, node-v57-darwin-x64-unknown, node-v57-linux-ia32-glibc, node-v57-linux-x64-glibc, node-v57-win32-ia32-unknown, node-v57-win32-x64-unknown, node-v64-darwin-ia32-unknown, node-v64-darwin-x64-unknown, node-v64-linux-ia32-glibc, node-v64-linux-x64-glibc, node-v64-win32-ia32-unknown, node-v64-win32-x64-unknown, node-v72-darwin-ia32-unknown, node-v72-darwin-x64-unknown, node-v72-linux-ia32-glibc, node-v72-linux-x64-glibc, node-v72-win32-ia32-unknown, node-v72-win32-x64-unknown, node-v83-darwin-ia32-unknown, node-v83-darwin-x64-unknown, node-v83-linux-ia32-glibc, node-v83-linux-x64-glibc, node-v83-win32-ia32-unknown, node-v83-win32-x64-unknown]
[2021-02-07T18:11:30.014Z] This problem can often be fixed by running "npm rebuild" on the current system
[2021-02-07T18:11:30.014Z] Original error: Cannot find module '/opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/grpc/src/node/extension_binary/node-v72-darwin-arm64-unknown/grpc_node.node'
[2021-02-07T18:11:30.014Z] Require stack:
[2021-02-07T18:11:30.014Z] - /opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/worker-bundle.js
[2021-02-07T18:11:30.014Z] - /opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/dist/src/nodejsWorker.js
[2021-02-07T18:11:30.014Z] internal/modules/cjs/loader.js:818
[2021-02-07T18:11:30.014Z]   throw err;
[2021-02-07T18:11:30.014Z]   ^
[2021-02-07T18:11:30.014Z] Error: Cannot find module './Worker.js'
[2021-02-07T18:11:30.014Z] Require stack:
[2021-02-07T18:11:30.014Z] - /opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/dist/src/nodejsWorker.js
[2021-02-07T18:11:30.014Z]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
[2021-02-07T18:11:30.014Z]     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
[2021-02-07T18:11:30.014Z]     at Module.require (internal/modules/cjs/loader.js:887:19)
[2021-02-07T18:11:30.015Z]     at require (internal/modules/cjs/helpers.js:74:18)
[2021-02-07T18:11:30.015Z]     at Object.<anonymous> (/opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/dist/src/nodejsWorker.js:45:14)
[2021-02-07T18:11:30.015Z]     at Module._compile (internal/modules/cjs/loader.js:999:30)
[2021-02-07T18:11:30.015Z]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
[2021-02-07T18:11:30.015Z]     at Module.load (internal/modules/cjs/loader.js:863:32)
[2021-02-07T18:11:30.015Z]     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
[2021-02-07T18:11:30.015Z]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
[2021-02-07T18:11:30.015Z]   code: 'MODULE_NOT_FOUND',
[2021-02-07T18:11:30.015Z]   requireStack: [
[2021-02-07T18:11:30.015Z]     '/opt/homebrew/Cellar/azure-functions-core-tools@3/3.0.3233/workers/node/dist/src/nodejsWorker.js'
[2021-02-07T18:11:30.018Z]   ]
[2021-02-07T18:11:30.018Z] }
[2021-02-07T18:11:30.020Z] Exceeded language worker restart retry count for runtime:node. Shutting down and proactively recycling the Functions Host to recover

Functions:

        test: [GET,POST] http://localhost:7071/api/test

[2021-02-07T18:11:30.169Z] Stopping host...
[2021-02-07T18:11:30.186Z] Stopping JobHost
[2021-02-07T18:11:30.205Z] Job host stopped
[2021-02-07T18:11:30.229Z] Host shutdown completed.
```

**Comment by fofiu** [comment] 2021-06-28 22:32
Any resolution to this issue?

**Comment by akozlov75** [comment] 2021-07-09 05:57
Guys, Gals anything going on with this issue? It's the middle of July already!

**Comment by vitor-l** [comment] 2021-07-12 14:34
Any response yet? OMG!

**Comment by fofiu** [comment] 2021-07-12 16:33
FYI -- As a work around I used `nvm` to install an intel based earlier version of node.js `14.16` in my case and I use that for running the Azure Function code locally.

**Comment by tobim-dev** [comment] 2021-08-07 11:48
It's interesting. I now tried multiple versions of node using `nvm`. Found out that version `10.24.1` worked as well as version `14.16.1`. However, the current LTS version `14.17.4` does not work. So for now I think it's best to stay with `14.16.1`.

**Comment by renoirtech** [comment] 2021-10-18 19:56
Guys, this worked like a charm for me: 

https://www.jurnalanas.com/node-js-mac-m1/

or 

https://dev.to/courier/tips-and-tricks-to-setup-your-apple-m1-for-development-547g

**Comment by JosefBackovsky** [comment] 2021-10-20 20:05
Any update?

**Comment by thecherrytree** [comment] 2021-10-26 01:59
The problem is that your current node version is installed using arm64, and there are certain bugs that are not compatible in azure-functions-core-tools that rely on the i386 (intel) installation of node. You can check if your node install is arm64 or i386 by going into your terminal and typing `arch`. If you are in the native M1 environment, you are going to see `arm64`. If this is the case, you need to get your terminal environment in the `i386` Rosetta environment. Below explains how to do this.

1. Open a terminal instance
2. type command `arch`
    - If `arm64`, go to step 3
    - if `i386`, go to step 5 - install nvm, install node 14.16.1 (last intel version) 
3. This step is only to be completed if your arch from step 2 is `arm64` . You are going to need to get a i386 terminal. Go to Apps > Utilities - duplicate your terminal. 
    - Once you duplicate the terminal rename the duplicate to `Terminal - Rosetta`. 
    - Right click the new terminal > Get Info > Select Open using Rosetta
    - Close
4. This step is only to be completed if you arch from step 2 is `arm64`. Open the new `Terminal - Rosetta` instance, check arch. It should be `i386`. If not, you need to check to make sure it is opening using Rosetta - see step 3.
5. Install NVM - `curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash`
6. Install node, but first check if you have the last intel version installed (if it was installed using an arm64 terminal, it's not going to work)
    - `node ls`
        -  if `14.16.1` is installed, uninstall it using `nvm uninstall 14.16.1`
    - `nvm install 14.16.1`
7. Blow away your terminal session where you've been running your npm app using azure-functions-core-tools and restart it. Run your app.

@mhoeger - this is a detailed work around. Most of the other instructions have bits and pieces of what folks need to do until this is sorted out. This gets more to the root of the issue.

**Comment by ejizba** [comment] 2021-10-28 16:48
Hey folks, I believe https://github.com/Azure/azure-functions-nodejs-worker/pull/417 may have fixed this particular M1 issue. We switched to a new grpc library which is pure JS and should not have any arch-specific requirements. The change was included in yesterday's release of the func cli, v4.0.3928, which I was able to install through npm. Please note v4 is still in preview - to get more info on upgrading from v3, see [here](https://docs.microsoft.com/azure/azure-functions/functions-versions?tabs=javascript%2Cv4#upgrading-an-existing-app). 

I will likely try to get an M1 Mac to test on myself, but y'all might beat me to the punch. Please let me know if you test on v4 and what results you see

**Comment by akozlov75** [comment] 2021-10-29 13:13
> Hey folks, I believe #417 may have fixed this particular M1 issue. We switched to a new grpc library which is pure JS and should not have any arch-specific requirements. The change was included in yesterday's release of the func cli, v4.0.3928, which I was able to install through npm. Please note v4 is still in preview - to get more info on upgrading from v3, see [here](https://docs.microsoft.com/azure/azure-functions/functions-versions?tabs=javascript%2Cv4#upgrading-an-existing-app).
> 
> I will likely try to get an M1 Mac to test on myself, but y'all might beat me to the punch. Please let me know if you test on v4 and what results you see

Looks like this release fix the issue, checked on my M1 - works fine. Thnx a lot guys/gals!

**Comment by ejizba** [comment] 2022-02-12 01:13
Closing this as fixed in https://github.com/Azure/azure-functions-nodejs-worker/pull/417. Please follow https://github.com/Azure/azure-functions-core-tools/issues/2834 for the remaining core tools support

**Closed as completed by ejizba** 2022-02-12 01:13 UTC
Labels: bug, P1, investigate
